version: '3.8'

services:
  base:
    image: imanelo/books_review_django:latest  # Use the image from Docker Hub
    volumes:
      - .:/code

  web_migrate:
    extends:
      service: base
    command: python manage.py migrate

  web_run:
    extends:
      service: base
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
